#pragma once
#include <iostream>
#include <string>
#include <queue>
#include <vector>
#include <fstream>
#include <cstdlib> 
#include <ctime> 
#include "AdditionalFunctions.h"
#include "CubeRepresentation.h"
#include "SolvingFunctions.h"
#include "ScrambleSimplifier.h"
#include "TestingFunctions.h"
